%% Demo ge_circle
% Example usage of the ge_circle function.
% 'help ge_circle' for more info.

output = ge_circle( -10, -10, 5000);
output2 = ge_circle( -10, -8, 5000, ...
                    'division', 3, ...
                    'name', 'Circle number 2, less divisions.', ...
                    'LineWidth', 5.0, ...
                    'LineColor', 'b8200bff', ...
                    'PolyColor', '00200bff');
output3 = ge_circle( -11, -9, 5000, ...
                    'division', 5, ...
                    'id', 'ge_circle3', ...
                    'visibility', 0 );
                
ge_output( 'demo_ge_circle.kml', [output output2 output3]);

