%% Demo ge_grid
% Example usage of the ge_grid function.
% 'help ge_grid' for more info.

output = ge_grid(-15, 0, -90, -60, ...
                'latRes', 0.5, ...
                'lonRes', 0.5, ...
                'name', 'grid example', ...
                'LineColor', 'ff20ff25', ...
                'PolyColor', '73ffe8ed' );

ge_output( 'demo_ge_grid.kml', output );