%% Demo ge_circle
% Example usage of the ge_circle function.
% 'help ge_circle' for more info.

x1 = -10;
y1 = -10;
x2 = -8;
y2 = -10;
x3 = -9;
y3 = -11;

output = ge_circle( x1, y1, 5000);
output2 = ge_circle( x2, y2, 5000, ...
                    'division', 3, ...
                    'name', 'Circle number 2, less divisions.', ...
                    'LineWidth', 5.0, ...
                    'LineColor', 'b8200bff', ...
                    'PolyColor', 'b8200bff');
output3 = ge_circle( x3, y3, 5000, ...
                    'division', 5, ...
                    'id', 'ge_circle3', ...
                    'visibility', 0 );
                
ge_output( 'demo_ge_circle.kml', [output output2 output3]);

