%% Demo ge_cylinder
% Example usage of the ge_cylinder function.
% 'help ge_cylinder' for more info.

output = ge_cylinder( -10, -10, 5000, 15000);
output2 = ge_cylinder( -10, -8, 5000, 20000, ...
                    'division', 3, ...
                    'name', 'Cylinder number 2, less divisions.', ...
                    'LineWidth', 5.0, ...
                    'LineColor', 'b8200bff', ...
                    'PolyColor', 'b8200bff');
output3 = ge_cylinder( -11, -9, 5000, 25000, ...
                    'division', 5, ...
                    'id', 'ge_cylinder3', ...
                    'visibility', 0 );
                
ge_output( 'demo_ge_cylinder.kml', [output output2 output3]);

