%% Demo ge_box
% Example usage of the ge_box function.
% 'help ge_box' for more info.

output1 = ge_box( 0, 40, -50, -10, ...
                    'altitude', 20);

output2 = ge_box( 20, 30, -40, 5, ...
                    'altitude', 5000, ...
                    'name', 'box number 2', ...
                    'LineWidth', 5.0, ...
                    'LineColor', '00ffa432', ...
                    'PolyColor', '40ff833e' );
                
                
ge_output( 'demo_ge_box.kml', [output1 output2] );

